"""Add instructor review fields to Session

Revision ID: 31e0eba5a81c
Revises: 7872baffd8af
Create Date: 2026-02-21 15:04:39.500633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31e0eba5a81c'
down_revision: Union[str, Sequence[str], None] = '7872baffd8af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('review_status', sa.Enum('PENDING', 'CONFIRMED_CHEATING', 'FALSE_POSITIVE', name='reviewstatus', native_enum=False), nullable=True))
    op.add_column('sessions', sa.Column('reviewed_by', sa.String(length=100), nullable=True))
    op.add_column('sessions', sa.Column('review_notes', sa.Text(), nullable=True))
    op.add_column('sessions', sa.Column('reviewed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'reviewed_at')
    op.drop_column('sessions', 'review_notes')
    op.drop_column('sessions', 'reviewed_by')
    op.drop_column('sessions', 'review_status')
    # ### end Alembic commands ###
