"""initial schema

Revision ID: 46ada9ad80b9
Revises: 
Create Date: 2026-02-15 12:46:45.256923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46ada9ad80b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('category', sa.Enum('MCQ', 'SUBJECTIVE', 'CODING', name='questiontype', native_enum=False), nullable=True))
    op.add_column('questions', sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficulty', native_enum=False), nullable=True))
    op.add_column('questions', sa.Column('subject', sa.String(length=100), nullable=True))
    op.add_column('questions', sa.Column('topic', sa.String(length=100), nullable=True))
    op.add_column('questions', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('questions', sa.Column('source', sa.String(length=200), nullable=True))
    op.add_column('questions', sa.Column('explanation', sa.Text(), nullable=True))
    op.add_column('questions', sa.Column('min_words', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('max_words', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('rubric', sa.JSON(), nullable=True))
    op.alter_column('questions', 'type',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.Enum('MCQ', 'SUBJECTIVE', 'CODING', name='questiontype', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'type',
               existing_type=sa.Enum('MCQ', 'SUBJECTIVE', 'CODING', name='questiontype', native_enum=False),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)
    op.drop_column('questions', 'rubric')
    op.drop_column('questions', 'max_words')
    op.drop_column('questions', 'min_words')
    op.drop_column('questions', 'explanation')
    op.drop_column('questions', 'source')
    op.drop_column('questions', 'tags')
    op.drop_column('questions', 'topic')
    op.drop_column('questions', 'subject')
    op.drop_column('questions', 'difficulty')
    op.drop_column('questions', 'category')
    # ### end Alembic commands ###
