"""Add Human-in-the-loop review fields to Session

Revision ID: 7872baffd8af
Revises: 46ada9ad80b9
Create Date: 2026-02-21 14:04:56.328697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7872baffd8af'
down_revision: Union[str, Sequence[str], None] = '46ada9ad80b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('scheduled_start', sa.DateTime(), nullable=True))
    op.add_column('exams', sa.Column('scheduled_end', sa.DateTime(), nullable=True))
    op.add_column('exams', sa.Column('is_published', sa.Boolean(), nullable=True))
    op.add_column('questions', sa.Column('category', sa.Enum('MCQ', 'SUBJECTIVE', 'CODING', name='questiontype', native_enum=False), nullable=True))
    op.add_column('questions', sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficulty', native_enum=False), nullable=True))
    op.add_column('questions', sa.Column('subject', sa.String(length=100), nullable=True))
    op.add_column('questions', sa.Column('topic', sa.String(length=100), nullable=True))
    op.add_column('questions', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('questions', sa.Column('source', sa.String(length=200), nullable=True))
    op.add_column('questions', sa.Column('explanation', sa.Text(), nullable=True))
    op.add_column('questions', sa.Column('min_words', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('max_words', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('rubric', sa.JSON(), nullable=True))
    op.alter_column('questions', 'type',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.Enum('MCQ', 'SUBJECTIVE', 'CODING', name='questiontype', native_enum=False),
               existing_nullable=False)
    op.add_column('sessions', sa.Column('review_status', sa.Enum('PENDING', 'CONFIRMED_VIOLATION', 'FALSE_POSITIVE', name='reviewstatus', native_enum=False), nullable=True))
    op.add_column('sessions', sa.Column('reviewed_by', sa.String(length=36), nullable=True))
    op.add_column('sessions', sa.Column('review_notes', sa.Text(), nullable=True))
    op.add_column('sessions', sa.Column('reviewed_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'sessions', 'users', ['reviewed_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'reviewed_at')
    op.drop_column('sessions', 'review_notes')
    op.drop_column('sessions', 'reviewed_by')
    op.drop_column('sessions', 'review_status')
    op.alter_column('questions', 'type',
               existing_type=sa.Enum('MCQ', 'SUBJECTIVE', 'CODING', name='questiontype', native_enum=False),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)
    op.drop_column('questions', 'rubric')
    op.drop_column('questions', 'max_words')
    op.drop_column('questions', 'min_words')
    op.drop_column('questions', 'explanation')
    op.drop_column('questions', 'source')
    op.drop_column('questions', 'tags')
    op.drop_column('questions', 'topic')
    op.drop_column('questions', 'subject')
    op.drop_column('questions', 'difficulty')
    op.drop_column('questions', 'category')
    op.drop_column('exams', 'is_published')
    op.drop_column('exams', 'scheduled_end')
    op.drop_column('exams', 'scheduled_start')
    # ### end Alembic commands ###
